### ISSUE TITLE
Neovide.app wont Open in Finder, but opens if alias in the terminal

### ISSUE THREAD

**Issue by goldcoders** [Kethku/neovide#1240]
Last time I compile before the last merge on bridge patch im not facing this...

well its good that the cli neovide is working now 
my only problem on that instance of neovide is i cannot override CMD + h 
if it is spawn using neovide cli.

Neovide.app the latest one I compile when double click or run 
Just wont start... if done on any GUI file explorer like finder...

I tried to use an alias on it and invoke in the terminal
and It start...

Is there a way both the cli and Neovide.app 
have the same instance?

its kinda side since I cannot find the instance or App being launch by the cli 
to point in macos keyboard to override it...

Looking forward for the next patch 

still thanks for this great project, I used it a lot in Rust :)

**Comment by goldcoders** [comment]
Ive checked the content of Neovide.app
it has the same cli neovide command on it
located at
/Applications/Neovide.app/Contents/MacOS/neovide

but if i create a symnlink i.e. to
~/.local/bin/neovide -> /Applications/Neovide.app/Contents/MacOS/neovide

Im surpise that it wont open the same instance of Neovide.app

the Neovide.app when opened is named Neovide
the cli when opened is named neovide

only the Neovide.app can be remapped in macos using custom keymaps...

For the time being i created  a bash function that will replace the neovide cli

```args
function neovide(){
    ARG="${1:-.}"
    CUR="$(pwd)"
    FILE="${CUR}/${ARG}"
    open -a Neovide.app --args $FILE
}
```

**Comment by jackrobbins1** [comment]
Bump. Having same issue. I can open neovide from terminal, but the bundled Neovide.app version doesn't launch from Finder.

**Comment by jfaz1** [comment]
Also having the same issue, I'm just launching from terminal for the time being. Does it work for anyone?

**Comment by StevenJPx2** [comment]
`The application cannot be opened for an unexpected reason, error=Error Domain=RBSRequestErrorDomain Code=5 "Launch failed." UserInfo={NSLocalizedFailureReason=Launch failed., NSUnderlyingError=0x600000054180 {Error Domain=NSPOSIXErrorDomain Code=111 "Unknown error: 111" UserInfo={NSLocalizedDescription=Launchd job spawn failed}}}`

**Comment by AdilZouitine** [comment]
Same issue for me

**Comment by caerphoto** [comment]
Same here, but to add an extra wrinkle, I _can_ open the Neovide.app bundle generated by cargo bundle, using `open target/release/bundle/osx/Neovide.app` in terminal, and it works just fine, but double-clicking the same .app from Finder does apparently nothing.

This is from compiling from main branch cloned yesterday, 16th March 2022.

**Comment by caraar12345** [comment]
Same here - `open -a Neovide` works fine, but not from Spotlight/Launchpad.

Same symptoms on my work MacBook (2019 16in Intel Pro) and personal MacBook (2020 M1 Air).

https://github.com/caraar12345/dotfiles for dot files 😄

**Comment by lowking** [comment]
Same here, This is from compiling from main branch cloned today, 24th March 2022.

**Comment by yanshay** [comment]
Found a workaround for now (working on MacOS 11.6.5):

sudo launchctl config user path /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

Reboot for settings to take effect

**Comment by wyc7758775** [comment]
Same here.

**Comment by areilly** [comment]
The problem about not being able to locate the nvim binary can be "fixed" by creating (and then editing) the correct path into the neovide config file, per https://neovide.dev/config-file.html
(Mine is in /opt/local/bin, because I installed it from MacPorts, and I notice that because hardly anything expects to look in /opt/local/bin, so I keep an eye out for that sort of thing.)

Still, this does not alter the finder-open problem, which seems to be vaguely related to the winit rust module, as mentioned above.

However, I have found that part of the problem could be getting the file path right: I've found that opening with open -a, or double-clicking in the Application directory, or Open with in the finder all result in nvim starting with CWD = /, which is why any named file that isn't actually in the root directory isn't found, and so it thinks that it's creating a new file, which is blank.
Dragging files to the app works because they're passed with a full path.  So does open -a Neovide.app --args $(realpath "$@")
