### ISSUE TITLE
[ArchLinux] Segmentation Fault when I close neovide window

### ISSUE THREAD

**Issue by kiuKisas** [Kethku/neovide#141]
When I exit neovide by closing the window (add not by typing `:qa`), I got a segmentation fault (core dump). 

I think it's an equivalent to `SIGTERM` event.

**Comment by Kethku** [comment]
This is a known issue but I can't seem to find the original. I may have accidentally closed it. This happens because the rendering loop doesn't realize when the neovim client has closed. I need some sort of global close triggering, but closing the process doesn't seem to be enough on other platforms.

**Comment by Kethku** [comment]
Is this still a thing? I will close if no response. I think this is fixed.

**Comment by kiuKisas** [comment]
Yeap, fixed :)
