### ISSUE TITLE
AltGr fix broke <M-C-> keybindings

### ISSUE THREAD

**Issue by svermeulen** [Kethku/neovide#186]
If I open a vanilla nvim-qt instance using vanilla nvim and hit `i<c-v><m-c-v>` then I will see the characters `<m-c-v>` as expected.  If I do the same in neovide, nothing is printed.   Neovide does detect `<m-v>` and `<c-v>` but not `<m-c-v>`

The same occurs for other `<m-c->` combinations

**Comment by Kethku** [comment]
Arg. Youre totally right, this is a side effect of the fix for norwegian keyboard layouts. The fix over there definitely causes the issue you are describing. 

The breaking change should be this commit:
https://github.com/Kethku/neovide/commit/c3b216df666e8e3b1e9539d82f32d84365bb6057

I have an idea based on that work which should make the input way more stable, but I need to try it first.

**Comment by Kethku** [comment]
This is now fixed. There are still key binding issues highlighted here: https://github.com/Kethku/neovide/issues/27
