### ISSUE TITLE
Alternative to neovim-lib

### ISSUE THREAD

**Issue by KillTheMule** [Kethku/neovide#20]
Hey, hope you don't mind this issue, feel free to delete/close it if you feel this is an intrusion.

I'm working on a [fork of neovim-lib](https://github.com/KillTheMule/nvim-rs) that I'd like to advertise a bit. It started with the idea to leverage async/await to allow for arbitrarily nested requests, but has grown into more of a rewrite, since I saw the chance to follow some ideas of my own :) It's definitely not API compatible, of course, but has already gotten some features I deem improvements.

If you're interested, I'd dearly like some feedback on it, and I'd certainly be open to requests/ideas, so if you want some influence on the lib you're using, it's a good time to get into touch.

Thanks for reading, and thanks for sharing your project :)

**Comment by Kethku** [comment]
Hey I'm definitely interested! One thing I've been considering doing which might be a good addition as well is taking my event parsing code found here: https://github.com/Kethku/neovide/blob/master/src/events.rs and upstreaming it to the neovim-lib or something similar. Neovim-lib just gives you raw message values which you have to validate and parse yourself. My wrapping enums make life a bit easier.

Can you be more explicit about the differences and improvements you've built over the neovim-lib?

**Comment by Kethku** [comment]
Ah yeah looks like youre planning on a type safe api instead of the Value type. Maybe my events code could be a good starting point. In any case collaborating on that part of the codebase would make my life WAY easier :)

**Comment by KillTheMule** [comment]
I see two sides of type safety. First, the "fixed" existing API, where I'd want to do all necessary conversions for the user by default (e.g. [`get_keymap`](https://github.com/KillTheMule/nvim-rs/blob/master/src/neovim_api.rs#L143) should not return something containing Values, but a proper rust type), and there's no risk of a panic (e.g. [`get_lines`](https://github.com/KillTheMule/nvim-rs/blob/master/src/neovim_api.rs#L64) should not panic if the response does not consist of an array of strings).

Secondly, there's user-generated events like in your case (for fixed events like `nvim_buf_lines_event` we should probably provide conversion functions), where we can't know the structure beforehand. I've written [this PR](https://github.com/3Hren/msgpack-rust/pull/228) to aid in providing useable conversion functions like you've implemented. Let's see how far we can drive this. But I'll also want to think about providing a serde-like macro `#[derive(try_from_value)]` to tag structs that provides a `TryFrom<Value>` implementation or something like this. But I've no experience with this, maybe rmpv-serde already provides something like this? It's more of a longer-time goal I think, unless someone can provide a solution :)

> Can you be more explicit about the differences and improvements you've built over the neovim-lib?

The main point would certainly be the usage of async/await to allow nested requests without explicitely spawning threads. I've reworked error handling, but it's not yet done, because it ties in with the next point: An API that enforces the event loop to be running appropriately, rather than runtime panics if one forgets to start the event loop. Both of this is done in my mind, but I'll need to code it up (that's my next step). I've also written up examples, in particular showing how to properly quit an addon (which wasn't properly possible with neovim-lib, in my opinion). More plans in the [Roadmap](https://github.com/KillTheMule/nvim-rs/issues/1) :)

I'll open up an issue about event parsing and notify you about it, let's see what we can come up with ;)

**Comment by Kethku** [comment]
I've taken a stab at swapping to nvim_rs, but found it pretty confusing. This is likely due to my lack of familiarity with rust's async support. In particular I am mostly familiar with c#'s async model which is a so called Hot async implementation. In such a model async functions begin running on a background thread immediately instead of waiting to be polled/awaited.

More specifically I am struggling to deal with interactions between the async runtime and the necessarily synchronous window thread via winit. I initially thought I could create a tokio channel and send commands from the window thread over to a task created solely for handling those commands. Unfortunately the act of sending the reciever over to the other thread caused it to close.

After that I got lost in the weeds trying to implement a blocking task which used a std channel to communicate across threads.

Ideally I would be able to move the window thread to be be managed by the tokio runtime. Unfortunately I don't have the foggiest idea how to go about doing that. Maybe I can manually pump the window thread? I'm pretty sure this isn't how winit is intended to be used.

I would really like to buy in fully to the async world as it would let me schedule tasks via timers etc which would be lovely. Unfortunately I'm not sure my understanding is there yet...

Bit long winded, but w/e :P @KillTheMule Got any suggestions/ideas? I'm at a loss. The current master holds my struggles

**Comment by KillTheMule** [comment]
I'm looking into it, but I have a hard time actually running that thing (I build master from HEAD~1, that worked, but I have various panics... I could figure out to set the font name, but not idea why it could not create a renderer). There are also no tests, so it's a bit tough to decide what works and what not. Can you provide some instructions?

**Comment by Kethku** [comment]
I can definitely give some pointers. I really appreciate your PR I plan on reading over it thoroughly. I have not reached the minimum feature set yet for a release which is why things are pretty rough at the moment.

First off, I'm running on windows, and do not have confirmation whether the app works for mac or linux. There have been a few people who have gotten it working however, and the dependencies should work out correctly. There has been some indication that running under wayland isn't supported currently because of an upstream issue: https://github.com/aclysma/skulpin

Other than that, there is an issue where any errors in your vim config can cause the app to fail. Further, font handling doesn't work properly if you haven't set the guifont to a valid value. It defaults searching for delugia nerd font which most systems don't have. All of these things are on the docket for fixing before an initial release.

In the meantime, you mentioned that it might be possible to setup a runtime which could run in collaboration with winit. I'm curious if you could give some more pointers for how that might work since winit tends to want to manage it's own event loop.

Feel free to back off though. You've done more than enough. I really appreciate the help!

**Comment by Kethku** [comment]
Ah I read your PR seems like async in the winit thread won't be possible. Thats reasonable and I can work around it given the notification strategy.

**Comment by KillTheMule** [comment]
> First off, I'm running on windows, and do not have confirmation whether the app works for mac or linux.

Uh, yeah, I'm on linux :) Can you give a hint on what non-rust dependencies I need? I'm runnig X, so no wayland problems coming. My config shouldn't error, I'm using neovim regularly, and it doesn't complain :) I was able to fix the font thingy in the code, but since the error message from the missing renderer wasn't clear I didn't keep on trying.

**Comment by Kethku** [comment]
https://github.com/Kethku/neovide/issues/22 the person in this thread mentioned intel-vulkan. Skulpin depends on Ash for it's graphics runtime which is a wrapper for vulkan libraries. I can do some more digging. On windows Vulkan just works :(

**Comment by KillTheMule** [comment]
Uhh ok, yeah, vulkan might be problematic. I'll investigate if I can get that working.

**Comment by Kethku** [comment]
Ok I've done some fiddling and got it running and building. I had to wrap the receiver half of the channel in an arc and mutex to send it over thread boundaries which I'm pretty sure shouldn't be necessary... This bumps into me not understanding the async patterns very well. One option that I read about recently was that async_std handles blocking differently. Maybe that would clean things up?

**Comment by Kethku** [comment]
After some more playing, some harder to solve bugs have been fixed by the move, but some new ones have cropped up. There is a pretty significant cost in complexity, but I think its fixable via some refactoring and further thought.

**Comment by KillTheMule** [comment]
> I'm pretty sure shouldn't be necessary

It's not. I'm not seeing why you did that though, the way I set it up in my PR did build, no need for the wrapping. The receiver is `Send`, but not `Sync`, but that's sufficient here. I'll comment in the PR directly :)



> One option that I read about recently was that async_std handles blocking differently. Maybe that would clean things up?

Not, `Send`/`Sync` are fundamental limitations you don't get around by using another runtime. In any case, you can't use `async_std` because you're spawning neovim as a child process, and `async_std` doesn't have the necessary features for that.

**Comment by Kethku** [comment]
This is working very well now. Closing as complete. Fixed a bunch of other bugs as well! Thanks for the suggestion.

**Comment by KillTheMule** [comment]
Let me know if I can help, or if you encounter pain points with nvim-rs
