### ISSUE TITLE
C-\ does not work on Mac.

### ISSUE THREAD

**Issue by arafune** [Kethku/neovide#2023]
Ctrl+\ does not work on my MacBook.

I have mapped the key C-\ to toggleterm. In Neovim (nvim) within the conventional terminal app, this key works correctly. However, I don't get any response when using NeoVide.

I suspect that the issue may be related to my Japanese keyboard layout, which treats the "\" key differently. As shown in the attached log file, when I press "\" with Ctrl, NeoVide recognizes it as "¥".

Can you please provide a solution to fix this problem?

OS: [macOS 13.5.2]
 - Neovide Version [e.g. 11.2]
 - Neovim Version [e.g. 0.9.2]
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/12581405/neovide_rCURRENT.log)

**Comment by fredizzimo** [comment]
I guess you have the OS configured to send `\` instead of `¥`?

Alacritty, which also uses winit has a similar issue, https://github.com/alacritty/alacritty/issues/6769. But that is for the plan `\` character. The bug report there is unclear if this has been fixed in the latest Alacritty with the latest winit or not. But there might still be problems with the ctrl combination.  

Can you test what the latest Alacritty version does, both in combination with ctrl, and without. And also ,what Neovide does if you type just the `¥` key?

I guess we should create an issue on https://github.com/rust-windowing/winit/issues, when we know better what's going on.

Anyway, you should be able to work around the issue by creating a recursive mapping
In vimscript
```vim
if exists("g:neovide")
    map <C-¥> <C-\>
endif
```
or lua
```lua
if vim.g.neovide then
    vim.api.nvim_set_keymap("", "<C-¥>", "<C-\\>" )
end
```

**Comment by fredizzimo** [comment]
That kind of mapping should already be possible with Neovim's built-in mapping, so we should not need to add special support for it. I'm not sure why it's not working for you, because I tested with
`:tmap <C-å> <C-\>`. And after that I'm able to exit the built-in terminal mode with `<C-å><C-N>` instead of the default `<C-\><C-N>` 

Maybe I did some mistake in in the lua, code that don't see right now (maybe the escaping). Can you try the vim version directly on the vim command line with `:`? 

I don't think the `|` that you see in insert mode is that relevant, it's just the ascii representation of the resulting control key. To see what neovim actually receives and what you should use for mapping you can go to insert mode and type `CTRL-V CTRL-¥`
