### ISSUE TITLE
Mouse click jump to the wrong position

### ISSUE THREAD

**Issue by jotacosta** [Kethku/neovide#218]
Hi, 

Mouse click-events jump to the wrong x,y position. This is not always a direct translation of +x, +y. It depend on how close you are from the (0,0) - Top-Left of the window. I.e: closer to (0,0) you jump less. By the time you're mouse clicking at the bottom the difference is considerably larger. 

I just assume that there is some conversion that is done from mouse events to the renderer.cs and that needs debugging. 

I was able to observe this in OSX, Linux (i3, and Gnome). I've compiled Neovide from scratch and I'm happy to further debug this if you point me to the right direction.  (I've been wanting to learn Rust anyway).

Hope it helps.

**Comment by Kethku** [comment]
for sure dpi issues :l 

On the neovide side this is handled here: https://github.com/Kethku/neovide/blob/master/src/window.rs#L33 and here: https://github.com/Kethku/neovide/blob/master/src/window.rs#L303

The first link shows where the new window size is swapped in the neovide side. The second one checks to see if the dpi has changed from frame to frame. If it has, it tries to adjust the window size to preserve the same grid size.

Unfortunately this is a bit of a hack since sdl2 doesn't understand dpi scaling very well. In my fork of skulpin we are still using the dpi scaling is defined as the current dpi compared to a set default dpi per platform. At least in principle this should give the correct dpi scaling factor, but in practice its kinda buggy. Others have reported issues as well...
https://github.com/Kethku/neovide/issues/217
https://github.com/Kethku/neovide/issues/216
https://github.com/Kethku/neovide/issues/213
https://github.com/Kethku/neovide/issues/212

I think the long term fix will be to swap back to the winit windowing system once the bugs are worked out. But last I tried I ran into significant issues. So I think in the meantime, getting off of my fork of skulpin and onto the upstream one which supports sdl2 now is a good strategy (plus its been pretty bad that I've been using the fork this long. Sorry @aclysma)

**Comment by Kethku** [comment]
If you're interested in attempting this I can give more guidance. I've been struggling to find the time and mental capacity to work on this the past week or so due to quarantine and general stress. I'd love any help I can get!

**Comment by jotacosta** [comment]
I can help, yes. I'm fluid in programming, not so much in Rust. But I've been trying to learn. I have a strong background in HCI so this project is perfect for me. 

Let me know how I can help. (And stay safe)

**Comment by Kethku** [comment]
Aight, first step I think would be to rebase upon the most recent skulpin master. The branch I'm using was just to get us up and running on sdl2, but Skulpin has since been updated and a bunch of bug fixes have gone in since then.

At a glance, the api has changed and there will be some difficulty with dpi handling, but just getting it building would be a huge step in the right direction.

**Comment by jotacosta** [comment]
Alright. I've change the cargo.toml. Skulpin 0.9.0 doesn't have `sdl2-static-link` anymore, so I've went ahead and removed that. Let me know if this is wrong. 

As predicted, there's a bunch of API changes and we need to work towards building it. I'm going to try my luck. 

I'll shoot you an email / chat here if I need your help. (I'm 100% I will, but at least I'll start doing something)

**Comment by Kethku** [comment]
Sounds good to me. We can make a PR to skulpin upstream once things are working to add back the sdl2-static-link

**Comment by Kethku** [comment]
I'm also on the gitter chat if that would be an easier way to discuss

**Comment by Kethku** [comment]
I believe this is now fixed. @jotacosta can you check?

**Comment by emiliaza** [comment]
Latest `master` still exhibits the issue on my high DPI display (macOS).

**Comment by j4qfrost** [comment]
A temporary fix was setting the scaling to 1, but the core issue was said to be upstream. I can investigate a fix if there are more Mac users with the problem.

@emiliaza can you give me your machine specs?

**Comment by emiliaza** [comment]
It's a 16" MBP with 6 cores i7, 16GB ram, radeon 5300M/intel UHD graphics 630.

**Comment by mborejdo** [comment]
I am also experiencing the "mouse offset" problem on a mbp


Hardware Overview:

      Model Name: MacBook Pro
      Model Identifier: MacBookPro15,1
      Processor Name: 8-Core Intel Core i9
      Processor Speed: 2,3 GHz
      Number of Processors: 1
      Total Number of Cores: 8
      L2 Cache (per Core): 256 KB
      L3 Cache: 16 MB
      Hyper-Threading Technology: Enabled
      Memory: 16 GB
     
Graphics/Displays:

    Intel UHD Graphics 630:
      Chipset Model: Intel UHD Graphics 630
      Type: GPU
      Bus: Built-In
      VRAM (Dynamic, Max): 1536 MB
      Vendor: Intel
      Device ID: 0x3e9b
      Revision ID: 0x0002
      Automatic Graphics Switching: Supported
      gMux Version: 5.0.0
      Metal: Supported, feature set macOS GPUFamily2 v1
      Displays:
        Color LCD:
          Display Type: Built-In Retina LCD
          Resolution: 2880 x 1800 Retina
          Framebuffer Depth: 24-Bit Color (ARGB8888)
          Main Display: Yes
          Mirror: Off
          Online: Yes
          Automatically Adjust Brightness: No
          Connection Type: Internal


    Radeon Pro 560X:
      Chipset Model: Radeon Pro 560X
      Type: GPU
      Bus: PCIe
      PCIe Lane Width: x8
      VRAM (Total): 4 GB
      Vendor: AMD (0x1002)
      Device ID: 0x67ef
      Revision ID: 0x00c2
      ROM Revision: 113-C980AL-075
      VBIOS Version: 113-C97501U-005
      EFI Driver Version: 01.A1.075
      Automatic Graphics Switching: Supported
      gMux Version: 5.0.0
      Metal: Supported, feature set macOS GPUFamily2 v1

**Comment by Kethku** [comment]
I believe this has been fixed
