### ISSUE TITLE
Macos Crash due to skulpin dropping object

### ISSUE THREAD

**Issue by j4qfrost** [Kethku/neovide#221]
```
libc++abi.dylib: terminating with uncaught exception of type std::__1::system_error: mutex lock failed: Invalid argument
Abort trap: 6
```

This seems to happen because when ui_loop finishes something is dropped manually and then automatically drops, causing the MoltenVK to try to destroy a buffer that doesn't seem to exist. Here are the relevant bits of the crash report:
```
10  libc++.1.dylib                	0x00007fff7056454d std::__1::mutex::lock() + 29
11  libMoltenVK.dylib             	0x0000000131e7069f MVKDevice::destroyBuffer(MVKBuffer*, VkAllocationCallbacks const*) + 31
```

I'm not sure about the specifics about why this happens, but I am able to resolve the issue by disabling either this line https://github.com/Kethku/skulpin/blob/c0b194833f97b839bd44a30fc2f17851b14e1016/src/renderer/renderer.rs#L461 or this line https://github.com/Kethku/skulpin/blob/c0b194833f97b839bd44a30fc2f17851b14e1016/src/renderer/renderer.rs#L463 for the upstream skulpin dependency. 

The above "fix" may lead to memory leaks.

**Comment by j4qfrost** [comment]
https://github.com/KhronosGroup/MoltenVK#memory-management

Maybe a better mind can make more sense of this than me.

**Comment by Kethku** [comment]
I think the correct step for handling stuff like this bug is to first rebase on the master version of skulpin. As is I think the fork we are using (my private fork for the initial sdl2 support) is not sufficient and has diverged too much. @jotacosta has started some work on this over here: https://github.com/Kethku/neovide/issues/218 but if necessary I can take a quick stab to get it done sooner.

Further @j4qfrost I have invited you as a contributor on the project. I really appreciate the bug reporting and general contributions you've been doing.

**Comment by j4qfrost** [comment]
Cool, thanks for the invite and kind words. I'll follow the issue. I took a look at the drop implementation for the most up-to-date version of skulpin, and it doesn't seem to be much different aside from the plugins dropping. Though I guess getting everyone on the same page is useful  in that we can start helping push skulpin development forward too.

**Comment by jotacosta** [comment]
I've started the port. I'm going slow as I'm not 100% fluent on Rust (things like lifetime are still new). But from what I can see, we should move to a logicalSize and try to not have dpi anywhere. This will require a bit of change in the code, as there are dpi validations in the current develop (with skulpin-sdl2) that don't exist in skulpin v0.9.0. 

If folks feel this is a priority and needs to be done soon, let me know.

**Comment by Kethku** [comment]
I think there are a number of bugs that are blocked behind this, but that doesn't necessarily make it urgent. I'd rather ramp people up and help people contribute than rush a given feature or bugfix forward.

The dpi changes were all hacks to be honest. I agree that using logical size is the way to go and then fixing any dpi issues upstream. I suspect most of the changes will be mostly tearing out dpi manipulation on our side rather than adding anything else.

Don't hesitate to reach out if you get stuck :)

**Comment by j4qfrost** [comment]
I was in the process of writing this when Kethku chimed in. I reiterated some of his points.

@jotacosta It's more like a "nice to have" going forward. For this issue, I've essentially smothered the error by not running code for macos, but I don't know if the destructor for the object is being run elsewhere or if it's just left in the wind until the program exits, which could lead to a memory leak. It would be helpful to be using the most up-to-date version of skulpin, but it's not a pressing issue. I'm personally going go back to my other project, but I'll to pop in to see if anyone needs Mac support and help out where I can with development.

I tried running neovide in valgrind, but there's a bad access, which I suspect happens because it runs a separate process for neovim. I get:
```
Process terminating with default action of signal 4 (SIGILL)
```

I'm still a bit dependent on rust auto suggestion tools for Sublime Text, but it really helps in a pinch. All of us need help sometimes.

**Comment by j4qfrost** [comment]
@Kethku We can fix this temporarily by adding process::exit at the end of ui_loop until we figure out a permanent fix. It'll keep the project looking more professional for the time being.

**Comment by exoticus** [comment]
@j4qfrost yeah that did alleviate the crashing however `q` still doesn't close neovide for some reason, the loop seems to break but the window remains open

**Comment by j4qfrost** [comment]
This seems to be resolved, I'll close it for now.
