### ISSUE TITLE
Cursor doesn't animate going to right

### ISSUE THREAD

**Issue by exoticus** [Kethku/neovide#225]
I have noticed that cursor animations doesn't work going to the right side whether while typing or simply hitting `l` all other directions animate correctly, i wonder if there's any reason for this? or is it a bug?

**Comment by exoticus** [comment]
So i found that it's intentional to prevent _lag_ however i tried to disable this behavior and see if there's actually any lag and couldn't notice any? Also i can't see why would that lag while hitting backspace erases a character while animating without causing lag

**Comment by Kethku** [comment]
Im not sure if I understand your second point... There is a long term task though regarding configuring when the cursor animates or not. Maybe this issue should be repurposed to allow that?

**Comment by Kethku** [comment]
Actually I think this issue is covered in this: https://github.com/Kethku/neovide/issues/117

**Comment by exoticus** [comment]
@Kethku i was talking about this 👇, What i mean is that i see that we already animate the cursor going to the left, like when you are deleting a character (with backspace) while animating doesn't seem to lag as the comment says.

```rust
if travel_distance.y == 0.0 && (chars_travel_x - 1.0).abs() < 0.1 {
   // We're moving one character to the right. Make movement immediate to avoid lag
   // while typing
   immediate_movement = true;
}   
```

Removing `immediate_movement` and allowing animation to the right doesn't seem to lag or impact typing for me hence my question wondering about the purpose of this

**Comment by Kethku** [comment]
@jonvaldes added it because he perceived lag while typing. I think the correct strategy is to make it optional and maybe disabled by default.

The issue I linked is for a task to add configuration for many types of cursor jumps. Many people don't want the cursor to jump to or from the command line as well, so handling that case in the configuration would be a good idea too.

If that task covers your needs, I'm going to close this one to just keep things tidy

**Comment by exoticus** [comment]
@Kethku sounds good to me, thanks for the awesome work!
