### ISSUE TITLE
session not saved when close window by clicking "X"

### ISSUE THREAD

**Issue by aj3423** [Kethku/neovide#232]
Quit handlers not invoked when click "x" to close Neovide window.  Which causes plugin like "xolox/vim-session" not clear locks on quit.
The "X" is handled correctly in Nvim-qt, what about add this feature to Neovide ?

**Comment by exoticus** [comment]
@j4qfrost this might be one of the flops of `process::exit` i think X would work more reliably if we delegate quitting to neovim so if user quits Neovide with `cmd+q` or simply using X, instead of breaking the ui loop ourselves and using `process::exit` we should call vim command `:qa` which in turn will gracefully quit vim causing bridge to return false to UI loop breaking it.

tldr; [instead of `break 'running`](https://github.com/Kethku/neovide/blob/92d7f472e6df6a01c3163268f13a87794ff0ca26/src/window.rs#L389) we send vim command `:qa`

**Comment by j4qfrost** [comment]
It might be because this doesn't get called,
https://github.com/Kethku/neovide/blob/92d7f472e6df6a01c3163268f13a87794ff0ca26/src/window.rs#L418,
so the quit event isn't processed by neovim. In that case the issue would
be that we're exiting early rather than because we're calling process::exit.

**Comment by j4qfrost** [comment]
Haha, that was a dumb comment. I'm awake now.

**Comment by j4qfrost** [comment]
@exoticus I think you're right. On a side note, @Kethku do we want to have draw_frame handling the condition for breaking the running loop? It might be better to check if we check if BRIDGE is still running explicitly in the loop so that shutdown logic is more verbose.

**Comment by Kethku** [comment]
@j4qfrost I'm not understanding your last sentence. Can you elaborate?

**Comment by Kethku** [comment]
This should be handled with this: https://github.com/Kethku/neovide/pull/234 Merging shortly unless I hear from @j4qfrost

**Comment by j4qfrost** [comment]
Sorry, I was predisposed. We can discuss this in gitter, since it's not really pressing.

So rather than returning false in draw_frame https://github.com/Kethku/neovide/blob/92d7f472e6df6a01c3163268f13a87794ff0ca26/src/window.rs#L297 to break out of `running we could check the running variable in BRIDGE to exit the loop. It's more a design decision for visibility and separation of concerns.

If we check in draw_frames then that implies that there was a problem with the drawing, which there isn't if the exit is triggered by BRIDGE closing, and so if we decide to print an error in that if statement, then it wouldn't accurately inform the user what the error is.

It may be better to give the BRIDGE a state object rather than just a running bool.

**Comment by Kethku** [comment]
I merged #234 @aj3423 can you confirm, did that fix your issue?

As for the draw_frame thing, I think it would make more sense to move the handling of this out of the bridge. The bridge originally was supposed to just manage sending of commands from the ui to the neovim process, and from the neovim process to the editor. This management of closing logic and honestly neovim process creation seems like it should be pulled out of the BRIDGE and into its own component.

What do you think?

**Comment by aj3423** [comment]
@Kethku The version in releases seems not patched yet, and I failed to build it myself, the final step says:
    
    # ~/neovide-git ❯ ~/.cargo/bin/cargo build --release
    error: could not find `Cargo.toml` in `/root/neovide-git` or any parent directory

Can you upload an executable here? I'll try it on both Windows and Linux.

**Comment by exoticus** [comment]
@j4qfrost yup i agree with you on having the draw method returning false be about drawing failures only, and bridge related exits may be handled separately, this would be the ideal state.

@Kethku well if we take the BRIDGE quite literally then yes it should only handle communication. But for the sake of conciseness couldn't we just rename the bridge to be neovim process manger and make it handle both communication and events?

**Comment by Kethku** [comment]
@aj3423 built artifacts can be found here: https://github.com/Kethku/neovide/actions/runs/70228511

**Comment by Kethku** [comment]
@exoticus my main concern at this point is that we've already run into some bugs related to not understanding the weird ins and outs of the BRIDGE component. So I'm hoping that by separating the concerns out a bit it would make it simpler and less error prone. I will make a PR to describe the kind of separation I'm thinking about

**Comment by aj3423** [comment]
@Kethku Seems fixed, tested on both Windows and Linux. Thanks!
