### ISSUE TITLE
Cannot start by click the icon.

### ISSUE THREAD

**Issue by arafune** [Kethku/neovide#2357]
**Describe the bug**
Cannot stat by clicking Neovide.app icon.  However, Neovide.app/Contents/MacOS/neovide can work from the terminal. 

**Screenshots**
<img width="897" alt="スクリーンショット 2024-02-10 22 16 12" src="https://github.com/neovide/neovide/assets/6754804/e34f5dec-069b-4772-b162-663316f1b85e">

 - OS: [ macOS 14.3.1]
 - Neovide Version [ 0.12.2]
 - Neovim Version [ 0.9.5]

**Comment by fredizzimo** [comment]
Can you either copy the output with the `y` key and paste it here or show the rest of it. 

The actual error is not visible. there's probably something in the `stderr` part.

**Comment by fredizzimo** [comment]
Can you make the window bigger, or scroll down?

**Comment by fredizzimo** [comment]
The problem seems to come from tmux, which should not run in a `non-interactive` shell, which Neovide launches.

The solution is a bit different depending on which shell you are using. But if it's zsh. then you need to move the tmux configuration from `.zprofile` to `.zshrc`.  For bash it should be in `.bashrc` instead of `.bash_profile` or `.profile`

**Comment by fredizzimo** [comment]
Yes, with status https://fishshell.com/docs/current/cmds/status.html

You should only setup tmux if the shell is interactive.
