### ISSUE TITLE
❯ ligature in terminal

### ISSUE THREAD

**Issue by onsails** [Kethku/neovide#266]
Neovide does ligatures rendering in normal mode (NERDTree) but fails to render "❯" ligature in terminal mode.
I have guifont set to set `FiraCode\ Nerd\ Font:h12`.

Terminal nvim:
![2020-05-01_01-27-52](https://user-images.githubusercontent.com/107261/80765293-5d290980-8b4b-11ea-8663-360746279b1c.png)

neovide:
![2020-05-01_01-29-39](https://user-images.githubusercontent.com/107261/80765312-6619db00-8b4b-11ea-9bbe-7b0833ebca1c.png)

**Comment by Kethku** [comment]
I could very well be wrong, but I think thats not a ligature? It looks like a special symbol in which case the bug is font fallback not working or the character not being present in the default fallback fonts

**Comment by onsails** [comment]
Yes indeed you are right, it's not ligature, it's a special character printed by [starship](https://starship.rs).
I have the same font in iTerm2 and `guifont` of Neovide but only Neovide fails to render it...

**Comment by Kethku** [comment]
yes likely iterm2 uses font fallback because the character doesn't exist in your configured font. Unfortunately due to the font management library options in rust at the moment, there isn't a good way to take advantage of operating system font fallback. SO to get around this I recently added a manual font fallback feature to the guifont configuration.

If you can find a font that for sure has that glyph supported, you can add multiple font names separated by commas in the guifont format.

For example: `let guifont=Consolas,FiraCode:h14`

This will set the first font to consolas, use firacode as a fallback, and set the font size to 14.

**Comment by onsails** [comment]
Perfect, thanks!
