### ISSUE TITLE
Does not launch on Windows

### ISSUE THREAD

**Issue by alexozer** [Kethku/neovide#296]
I've built Neovide on my Windows 10 system and when I run neovide.exe, nothing appears to happen. No window pops up or anything. Running from the terminal produces no logs either, let me know if there's a way to get more verbose log output.

I'm using a Radeon RX 570 with the latest driver.

**Comment by j4qfrost** [comment]
Can you run the program with --log?

**Comment by alexozer** [comment]
Hm, it seems like reinstalling neovim through chocolately did the trick. Not clear it was ever out-of-date or anything though.

**Comment by j4qfrost** [comment]
It probably means that you were missing a dependency. Would you mind building the project and telling me if it worked? It would be greatly appreciated @alexozer

**Comment by alexozer** [comment]
I originally built this project from source, and it just wouldn't launch until I reinstalled neovim through chocolately. Let me know if there's something else you'd like me to do besides building this project though.

**Comment by j4qfrost** [comment]
So chocolatey probably fixed the issue, because you were lacking the appropriate dependencies. The installed binary for neovide probably works, but I want to confirm that ```cargo run``` works, because there might be a chance that there is a problem that was introduced in code. I want to try to narrow down whether it was a dependency issue or a code issue. If ```cargo run``` works, then we're all good.
