### ISSUE TITLE
Add app icon to executable on linux and mac

### ISSUE THREAD

**Issue by prabirshrestha** [Kethku/neovide#31]
It is a GUI app after all :)

Not in hurry but nice to have. Might be for now can just use the default neovim assets?

**Comment by Kethku** [comment]
I was thinking about what icon I wanted. I did some research and it looks like the license for the rust gear icon is such that modification for other icon purposes is allowed, so maybe something like that with the neovim logo in it? Not sure.

In the meantime the default neovim asset is a good suggestion

**Comment by Kethku** [comment]
Done for windows. Not sure how to embed the icon in the build binary for mac and linux

**Comment by prabirshrestha** [comment]
Might be look at how wezterm and alacritty does it?

**Comment by Kethku** [comment]
Wezterm and Alacritty do it as a build step in their pipelines. I have handled this problem on windows via a rust build.rs script which I find highly preferable as it simplifies getting started with the project. I would like to have a solution which runs in the build.rs script for linux and mac, but since I don't own a mac and have not setup a linux box recently, I don't have a way to build such a solution on my own.

Any help would be much appreciated.

**Comment by Kethku** [comment]
This is solved by cargo bundle
