### ISSUE TITLE
By spacevim, guifont not work

### ISSUE THREAD

**Issue by JonasGao** [Kethku/neovide#398]
i`m using https://github.com/SpaceVim/SpaceVim with neovim, and gui is neovide. and the guifont is not working.

![image](https://user-images.githubusercontent.com/4549584/100414169-0c16cf00-30b4-11eb-90b3-a89da87fc895.png)

**Comment by Kethku** [comment]
I believe the font you have specified is missing the special characters necessary to render the status bar. Do you have a font that has all of the powerline characters installed? If you do, you can specify that font name after the first one separated by a comma kinda like this: guifont = "CaskaydiaCove NF,Delugia Nerd Font:h10" where Delugia Nerd Font would be the second font name.

As an aside, this is necessary because we don't have cross platform support for font fallback implemented. So for now you have to specify the fallback manually.

**Comment by weiss-d** [comment]
Hi, @Kethku!
In fact the `guifont` setting doesn't work at all. Neovim and Neovide windows on the screenshot have different fonts at a closer look.
I have the same problem with the latest SpaceVim and Neovide 0.6.0-8 built from AUR on Arch Linux.
Neither this setting changes font face, nor size.
I will highly appreciate any clue on how I can change the font and size for your implementation.

**Comment by Kethku** [comment]
I'm guessing the font name you are using is not correct? Is Tru replacing the space with an underscore or similar

**Comment by weiss-d** [comment]
> I'm guessing the font name you are using is not correct? I'd try replacing the space with an underscore or similar

The font name is correct, this setting is just does not work for `neovide`, while the setting given in comments in #446 works.

**Comment by ptaranat** [comment]
I found a solution. Spacevim creates a symlink from `AppData/Local/nvim` to `~/.SpaceVim`. Neovide relies on `init.vim` in this folder, but Spacevim uses `init.toml`. Setting `guifont` in `init.toml` does not affect Neovide because those changes are not applied from terminal.

To fix this: edit `~/.SpaceVim/init.vim` to have `set guifont=Your\ Font:h14`

However, this doesn't change the case where the font is still missing glyphs. In my case, Meslo and FiraCode work fine.
