### ISSUE TITLE
[Blurred Floating Windows] broken with vim-clap

### ISSUE THREAD

**Issue by kiuKisas** [Kethku/neovide#432]
See screenshot below.
Maybe due to `vim-clap` using `floating_win` or maybe due to the background render by vim-clap ? Can't tell..
Neovide with multiGrid:
![image](https://user-images.githubusercontent.com/12698940/103552745-ab499600-4eac-11eb-9474-74f0839ff713.png)
Neovim:
![image](https://user-images.githubusercontent.com/12698940/103553086-3a56ae00-4ead-11eb-9899-af453560c886.png)

**Comment by duvallj** [comment]
Related to #14 ?

**Comment by kiuKisas** [comment]
Yeay, also to these more recent:
-  commit: https://github.com/Kethku/neovide/commit/1d981f3c2ce56d3c333a2d12fd0c4647119eeaa4
- this README section: https://github.com/Kethku/neovide#blurred-floating-windows

**Comment by Kethku** [comment]
Yeah this makes sense. Currently blurred windows are applied to all floating windows. I don't really know yet of a good way to stop this from happening/I don't have a system to specify per window options that can get synced to the front end.

Ideally I would love to have the system track the built in window transparency option so that it works with vanilla transparent floating windows, but I haven't spent the time to figure out how to do that yet. If anybody has any ideas for what that might look like, I'm all ears.

**Comment by RedBeard0531** [comment]
Similar issue with https://github.com/nvim-telescope/telescope.nvim

**Comment by fourbytes** [comment]
Having the same issue here with CoC (symbol rename and code action menus).

**Comment by Kethku** [comment]
Ah yes. I'm actively working on how to fix this, but its somewhat involved. I'd appreciate patience :)

**Comment by lf-** [comment]
I found it helpful as a workaround to `let g:neovide_floating_blur = 0` so at least the text just has poor contrast if this happens and is not additionally blurred.

**Comment by kiuKisas** [comment]
here a screenshot with @lf- workaround:
![image](https://user-images.githubusercontent.com/12698940/111761391-20b7e680-88a0-11eb-85b2-20155687efa3.png)

**Comment by p00f** [comment]
Aren't these clap/telescope issues? Normal floating windows render properly
![image](https://user-images.githubusercontent.com/36493671/112098336-9d600300-8bc7-11eb-9744-a5d537515d32.png)
Only telescope is broken
![image](https://user-images.githubusercontent.com/36493671/112098309-90dbaa80-8bc7-11eb-9e38-75cf14122fd7.png)

**Comment by Kethku** [comment]
The difference is that telescope and some other plugins use multiple floating windows to create the border effect.

Because neovide doesn't pay attention to the buffer local transparency settings, the system blurs the background.

The fix is complicated because neovide today doesn't pay attention buffer local options or settings, only global ones. So its a big change to add support to the settings system for it.

**Comment by Kethku** [comment]
Closing in favor of more detailed https://github.com/Kethku/neovide/issues/720
