### ISSUE TITLE
Error when pasting and writing accented chars

### ISSUE THREAD

**Issue by szaffarano** [Kethku/neovide#448]
If a file has accented characters like `á`, I can edit and modify it without any issue.  But when I try to paste an accented character using the OS clipboard (from `+` register), I get:

![Screen Shot 2021-01-19 at 14 14 14](https://user-images.githubusercontent.com/58266/105069420-ac5bf500-5a60-11eb-9d62-ee84a1ebda02.png)

Instead of
```
áéíóúñ
```
And if I save the pasted text:
```
❯ cat -e /tmp/test.txt
M-^GM-^NM-^RM-^WM-^\M-^V$ 
```
When I try to write one of these chars, I can't, and instead of writing something, it returns from edit to command mode.

Same actions using neovim on the console work fine.

Am I missing some specific configuration?

- Neovim v0.4.0
- Neovide v0.6.0
- Both macOS Catalina and Arch Linux

**Comment by Kethku** [comment]
Thats very strange. Neovide doesn't do anything to the clipboard as far as I know... Let me see if I can repro the issue

**Comment by Kethku** [comment]
On windows I don't have this issue. Maybe this is an sdl2 problem? I'm a bit at a loss... The inputing of such characters is a known bug because neovide currently only supports the qwerty keyboard layout. However there is an interim path for solving that issue which is to add your keyboard layout to the keyboards list. If you interested in that path I can give some more details about how to make a PR with such a change. Long term I hope to fix keyboard input using upstream winit improvements. Details can be found here: https://github.com/Kethku/neovide/issues/445

**Comment by gasacchi** [comment]
neovide only support for qwerty? how to add support for colemak layout?

**Comment by Kethku** [comment]
Currently the way to do it is by adding a layout like this one: https://github.com/Kethku/neovide/blob/main/src/window/sdl2/layouts/qwerty.rs

However as I mentioned above the hope is for this to be fixed upstream so we don't have to do such nasty hacks

**Comment by Kethku** [comment]
I can't repro this issue. Seems to be working now.

**Comment by szaffarano** [comment]
Hi @Kethku Sorry for the delay!
Yes, not it works fine.  Thanks
