### ISSUE TITLE
Does not respect my Xmodmap

### ISSUE THREAD

**Issue by lijaesela** [Kethku/neovide#479]
This has happened to me before with other programs, where some use keycodes and other use keysyms.
For example, when I try to enter <C-u> (which I enter on my laptop as Super + u with my Xmodmap, because my ctrl key is broken), rather than page up, neovim tells me "already at oldest change", as if I only pressed 'u'.

This is small, very platform specific, and frankly probably not on any list of priorities, but it would make this program useable in fringe cases like mine.

**Comment by Kethku** [comment]
I actually think this is relatively high priority because it represents an issue with the way that keyboard input is handled. However its unlikely to get solved until we switch to winit and the hopefully upcoming rewrite of the keyboard input api.

This issue https://github.com/Kethku/neovide/issues/445 tracks the effort

**Comment by mablin7** [comment]
Hey, I'm having the same issue with my remapped caps lock. Is there maybe a temporary workaround?

**Comment by Kethku** [comment]
I believe this has been fixed in main. Please reopen if either of these problems persist.
