### ISSUE TITLE
Cursor animation in insert mode

### ISSUE THREAD

**Issue by carljcruz** [Kethku/neovide#518]
Hi! I just want to ask if there is a way to increase the speed of the cursor animation when inside insert mode? Because whenever I'm typing anything, it feels like theres a delay because the | cursor lags behind with the animation.

Like this
![image](https://user-images.githubusercontent.com/48541404/113899365-509f3d80-97ff-11eb-935f-aedd51bc08c7.png)

See how the w is already there but the cursor is still in the middle of q and w? 

I tried using the  neovide_cursor_animate_in_insert_mode setting but I kinda missed the fluidity of the default setting.

Thank you in advance!

**Comment by PyGamer0** [comment]
Did you try changing the value of `g:neovide_cursor_animation_length`?

**Comment by Kethku** [comment]
setting that will effect the animation length for all cursor animations, not just insert.

You could live change it in your vim config in an autocommand whenever you enter or exit insert mode, but I think long term we will want to add more configurability.

I believe this issue is covered by https://github.com/Kethku/neovide/issues/117
