### ISSUE TITLE
Control-Forwardslash Key Combo is interpreted as only a forwardslash

### ISSUE THREAD

**Issue by neelkarma** [Kethku/neovide#528]
In terminal neovim, if you go into insert mode in an empty buffer and do a Control-Forwardslash key combo, you should get `^_` in the buffer. In neovide, if you do the same thing, you only get `/`. Also afaik this is only a problem with Control-Forwardslash as when I try Control-Backslash I get the expected output (`^\`).

The problem I have is that I want to remap `<C-_>` (control-forwardslash) to something, but it isn't working in neovide as it interprets control-forwardslash as only a forwardslash.

OS: Windows 10
Neovide Version: 0.7
Neovim Version: Latest Nightly
Keyboard Layout: US (QWERTY)

**Comment by Kethku** [comment]
This is due to the way your terminal handles keyboard input. If you run Neovide (or nvim-qt) and bind <C-/> rather than <C-_> you find it works as you expect. I'm not sure why C-_ is handled in neovim when run under a terminal, but it doesn't make much sense to me.

I'm open to changing the input system, but given that nvim-qt works similarly, I'm not sure if its the correct action

**Comment by neelkarma** [comment]
It looks like `<C-/>` works fine in neovide and nvim-qt but not terminal, and `<C-_>` works in terminal but not neovide and nvim-qt... Well for now I'm just checking whether neovim is being run in the terminal or not:
```vim
if $TERM=~'vtpcon'
	nmap <C-_> <Plug>kommentary_line_default
	xmap <C-_> <Plug>kommentary_visual_default
else
	nmap <C-/> <Plug>kommentary_line_default
	xmap <C-/> <Plug>kommentary_visual_default
endif
```
and everything seems to be working fine! Thx for the help
