### ISSUE TITLE
FiraCode Nerd Font - Glyphs Not Showing

### ISSUE THREAD

**Issue by ztroop** [Kethku/neovide#578]
Using the [FiraCode Nerd Font](https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/FiraCode) causes missing glyphs/symbols in `neovide`. I don't have this issue in the other terminals or editors I've used that use the same font. 

```
set·guifont=FiraCode\·Nerd\·Font:h18
```

Thoughts?

**Comment by PyGamer0** [comment]
which glyphs are missing?

**Comment by Kethku** [comment]
I believe this is a font fallback issue. Most fonts don't have all the glyphs, and because this is written in rust, we don't have a good system for selecting a font to render glyphs not in the font.

If you know what glyphs are missing and have a font that contains them, you can list it in the guifont by separating font names by a comma

**Comment by Kethku** [comment]
Otherwise this will be fixed by https://github.com/Kethku/neovide/issues/444

**Comment by p00f** [comment]
You can still specify fallback fonts like `set guifont=Fira\ Code,PATCHED_NERD_FONT:h18`

**Comment by ztroop** [comment]
Confirmed, setting a fallback does the trick. 😄 Thanks!
```
set·guifont=FiraCode\·Nerd\·Font,DejaVuSans:h18
```
