### ISSUE TITLE
How does one paste from the system?

### ISSUE THREAD

**Issue by nerdo** [Kethku/neovide#642]
This may seem like a silly question, but I haven't been able to figure it out.

How does one paste from the system into neovide?

In a termnial, i normally CTRL+SHIFT+V to paste from the system, but that doesn't seem to work with neovide and I can't seem to find any information on how to do this.

**Comment by nerdo** [comment]
Thank you, I had no idea those registers existed!

**Comment by Midren** [comment]
I think that support for CRL+SHIFT+V should be added, because if you are running remote-tcp mode, an approach with the system clipboard is not possible, as I want to paste from another system.

**Comment by nonetrix** [comment]
I have this in my init.vim and it let's me do this
```
noremap <C-C> "+y
noremap <C-V> "+p
```
however I can't get it to work when I am in command mode or ```:```

**Comment by dineshKumar777** [comment]
> I have this in my init.vim and it let's me do this
> 
> ```
> se mouse+=a
> 
> noremap <C-C> "+y
> noremap <C-V> "+p
> ```
> 
> however I can't get it to work when I am in command mode or `:`

@nonetrix you need to use cnoremap for command mode. in command normal mapping wont work. you can use middle click or as follows

```vim
cnoremap <C-V> <C-r>+
```
ref: https://stackoverflow.com/a/48483759

**Comment by nonetrix** [comment]
> > I have this in my init.vim and it let's me do this
> > ```
> > se mouse+=a
> > 
> > noremap <C-C> "+y
> > noremap <C-V> "+p
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > however I can't get it to work when I am in command mode or `:`
> 
> @nonetrix you need to use cnoremap for command mode. in command normal mapping wont work. you can use middle click or as follows
> 
> ```viml
> cnoremap <C-V> <C-r>+
> ```
> 
> ref: https://stackoverflow.com/a/48483759

Thanks seems to work thanks! however would be nice to be able to do it in insert mode, but I'm sure it's a similar process

**Comment by Kethku** [comment]
note: I highly recommend getting used to the default editor bindings when it comes to standard text editing features. This lets you use other vim integrations comfortably without configuration

Plus not reaching for ctrl is marginally more ergonomic.

**Comment by fredizzimo** [comment]
Well, I would say that `<C-c>` is more ergonomic than `"+y` when you want to copy to the system clipboard.

But there's another option personally I set `set clipboard=unnamedplus` in my `init.vim`, which makes all copy and paste operations inside Vim use the system clipboard by default.

But then I also use https://github.com/svermeulen/vim-cutlass, and 
```
nnoremap x d
xnoremap x d

nnoremap xx dd
nnoremap X D
```
So that I always explicitly have to use `y`, when I want to copy and `x`, when I want to cut. This means that the clipboard is not constantly overwritten with things when you edit. For me that is much more ergonomic, since I can easily delete stuff after I have cut or copied something without loosing easy access to the previously copied stuff. Also very often when I substitute something, I want to do it in multiple places, which normally requires use of special registers to make repeatable.
