### ISSUE TITLE
Set WM_CLASS or WM_INSTANCE 

### ISSUE THREAD

**Issue by Federico-Ciuffardi** [Kethku/neovide#704]
I would like to be able to change the WM_CLASS or WM_INSTANCE properties of the noevide window (see the [link](https://www.x.org/docs/ICCCM/icccm.pdf) for more information on those properties).

Something like [st](http://manpages.org/stterm) `-c` flag.

**Comment by Kethku** [comment]
Can you give more details? Is this linux specific? What are WM_CLASS and WM_INSTANCE for?

**Comment by Federico-Ciuffardi** [comment]
Yes, it is Linux specific. Actually it's [xorg](https://www.x.org/wiki/) specific (used by most linux window managers). 

I use it to set a specific class (`notes` for example) for a vim instance with my notes. Then I set up a shortcut that shows me the window class=`notes` and if it doesn't find a window with that class, it opens a vim instance with my notes and the class set to `notes`. This allows me to access my notes quickly and also avoid multiple instances. A window like this is called a [scratchpad](https://i3wm.org/docs/userguide.html#_scratchpad).

**Comment by TimB87** [comment]
So, [winit](https://docs.rs/winit/0.16.0/winit/os/unix/trait.WindowBuilderExt.html#tymethod.with_class) supports defining a class. I feel like the correct way to implement a this feature request we would need to actually set the class, and make it overrideable via a clap argument, e.g. `-c, --class`.

In order to be correct about things, we need to consider the same thing for waylands `app_id`.

**Comment by last-partizan** [comment]
https://github.com/rust-windowing/winit/blob/c916eb613734b389d7add7efec7f698ca739bae2/src/platform_impl/linux/x11/window.rs#L301

Looks like we don't need special argument, this could be done by using variable `RESOURCE_NAME`.

@Federico-Ciuffardi could you try it?
