### ISSUE TITLE
guifont not properly bolding the font

### ISSUE THREAD

**Issue by AnsonH** [Kethku/neovide#709]
I'm using the [MesloLGS NF][1] font with font weight of bold (`:b`) as configured in `init.vim`:
```
set guifont=MesloLGS\ NF:h14.5:b 
```

However, it seems like the bold font weight is not applying to the text of the file. The name of the file in the tabline ("init.vim" in red background) is in bold font weight though. This issue is present in **v0.5.0** as well as in **v0.7.0**.

![Bold font weight not applying](https://user-images.githubusercontent.com/57580593/120919697-8a040480-c6ed-11eb-9753-41b9326d2bd0.png)

To prove that my font is properly installed, here's a screenshot from my Windows Terminal showing what the expected results should look like:

![Windows Terminal](https://user-images.githubusercontent.com/57580593/120919796-0565b600-c6ee-11eb-8da3-0ad2366b8259.png)

Here's some useful information about my environment:
- OS: Windows 10 version 20H2
- neovim version: v0.5.0-dev+1325-gdab6b08a1
- Color scheme: [sonokai][2]

Thank you very much!

[1]: https://github.com/romkatv/powerlevel10k#manual-font-installation
[2]: https://github.com/sainnhe/sonokai

**Comment by PyGamer0** [comment]
related to #457

**Comment by gshpychka** [comment]
@PyGamer0 it's a bug, though, not an enhancement.

**Comment by Kethku** [comment]
It's fine either way. The difference is unimportant for bugs like this which don't break core functionality. We will get to it eventually

**Comment by gshpychka** [comment]
You say it's unimportant, but bugs like these make the tool unsuitable for actual use, since the way the font looks is so important for a text editor. 

I do understand that there are more broken places that need to be fixed, though.

**Comment by Kethku** [comment]
The unimportant bit is whether this is a bug or an enhancement. The issue is important.

Fixing it would not be overly difficult but touches some code that changed recently to enable font fallback. If you're interested in pushing this forward, I can give some hints for what it might look like. Let me know and I'll give some more details about the parts that should change.

**Comment by gshpychka** [comment]
>The unimportant bit is whether this is a bug or an enhancement. The issue is important.

I realize now that I misread your previous comment, disregard.

**Comment by smolck** [comment]
> Fixing it would not be overly difficult but touches some code that changed recently to enable font fallback. If you're interested in pushing this forward, I can give some hints for what it might look like. Let me know and I'll give some more details about the parts that should change.

@Kethku I'm happy to try and fix this given those hints/details, if you wouldn't mind/when you get the chance?

**Comment by Kethku** [comment]
Ok! Step zero would be to modify the guifont option parser to track bold modifiers and such https://github.com/Kethku/neovide/blob/main/src/renderer/fonts/font_options.rs#L9. Its been a while since I looked at that code but I think it would involve parsing a new component with a b prefix similar to how we parse the height https://github.com/Kethku/neovide/blob/main/src/renderer/fonts/font_options.rs#L28.

Then I would modify the font shaping. Currently the shaping and fallback system is a big jumble in the caching shaper. The renderer interacts with the caching shaper via the shape_cached function https://github.com/Kethku/neovide/blob/main/src/renderer/fonts/caching_shaper.rs#L252 which takes bold and italic arguments. Those arguments go into a "ShapeKey" which is used to cache the resulting shaped blobs of text. However currently the shape function ignores those properties :(. So implementing the extra font style info at all would require piping those into the shape function.

To handle the new font style in the shaper, the FontLoader would need to be changed to take bold and italic booleans here: https://github.com/Kethku/neovide/blob/main/src/renderer/fonts/font_loader.rs#L123. I'd probably rename the current FontKey to FontSelection and then create a new FontKey struct with a FontSelection, bold and italic fields. Then I'd modify https://github.com/Kethku/neovide/blob/main/src/renderer/fonts/font_loader.rs#L94 and https://github.com/Kethku/neovide/blob/main/src/renderer/fonts/font_loader.rs#L99 to instead of just use the default style, take into account the bold and italic options. Details about the style struct can be found here: https://github.com/rust-skia/rust-skia/blob/cf6e02c936fc47e1c1254bddb55693b451d370fb/skia-safe/src/core/font_style.rs#L129. Any option from full fledged float values to just on off may make sense here. I'm not sure what is best, so I'm good with w/e

After the font loader is modified I think it should be as simple as passing the bold and italic options through from the shape function on to the load_or_get call on the font shaper and we should be home free. Side note: doing it this way should fix both this issue and the fact that font style isn't taken into account when rendering highlighted text such as is common in some colorschemes where comments are italicized.

Thanks for the push btw, writing out game plans for features like this makes it much more likely that I will get to these regardless of whether you do. Its a great way to organize thoughts around an issue.
