### ISSUE TITLE
Fonts not rendering on certain places.

### ISSUE THREAD

**Issue by PyGamer0** [Kethku/neovide#723]
![image](https://user-images.githubusercontent.com/64531844/121843807-947f5900-cd00-11eb-9fcf-88c0d264b34e.png)

As seen in the above screenshot; in some places the font is not rendering. (latest main branch)
My current guifont is:
```viml
set guifont=Iosevka\ Custom,DejaVuSansMono\ NF:h16
```
if i change it to
```viml
set guifont=DejaVuSansMono\ NF:h16
```
it works
but if i change it to
```viml
set guifont=Iosevka\ Custom:h16
```
it stops working

**Comment by last-partizan** [comment]
Yes, i'm facing similar issue:

with
```
set guifont=JetBrainsMono\ Nerd\ Font,DejaVu\ Sans\ Mono,Iosevka,DejaVu\ Sans,Droid\ Sans\ Fallback:h24
```
![image](https://user-images.githubusercontent.com/301015/121955710-f5427c00-cd68-11eb-9722-2db9ad18a2be.png)


with
```
set guifont=Iosevka:h24
```
![image](https://user-images.githubusercontent.com/301015/121955820-0e4b2d00-cd69-11eb-8701-8b7f71b2879a.png)

**Comment by anirudhb** [comment]
I'm facing a similar issue on the OpenGL branch on the last word in a line (when there is no highlighted word after it):
![image](https://user-images.githubusercontent.com/9709011/122626893-8cf1e400-d061-11eb-83ad-55a430c4bd0d.png)

**Comment by Kethku** [comment]
The opengl branch is no longer in development. Please use main.

**Comment by tpict** [comment]
I'm seeing something similar with a fresh build from the main branch. The git status indicator in my shell prompt (something like `master• ❱`) is invisible, but occupies the space it would normally. Interestingly, if I place a cursor over the space where a character should be, it is drawn:

<img width="432" alt="image" src="https://user-images.githubusercontent.com/12588098/122657509-f2ed7280-d118-11eb-8ee0-fbea716d99fd.png">

**Comment by anirudhb** [comment]
I believe the issue seems to be that the size of the text region is computed incorrectly, as currently, Neovide assumes that all characters are the same width (when e.g. ligatures and emoji/special characters) can make the text longer than a simple `len(text) * avg_width` (which is how it's currently computed [here](https://github.com/Kethku/neovide/blob/main/src/renderer/mod.rs#L98-L103)

**Comment by Kethku** [comment]
@anirudhb saved me from writing a big chunk of text :P I do appreciate you digging in though. I have some ideas, but if you come up with something I'd love to hear about it.

**Comment by anirudhb** [comment]
I was able to find a fix for my case: the issue was that when shaping a run of text which included control characters, all the other text in the blob would also be dropped as well. I'm preparing a PR currently to fix this, and it is working for me:
![image](https://user-images.githubusercontent.com/9709011/122701654-91093780-d202-11eb-94d2-cb9f320af8a4.png)

**Comment by Kethku** [comment]
I just pushed a fix for the other half of this issue :P turns out if font fallback happened not at the start of a line of text, the first part was getting dropped. Between the two of us I think this issue is fixed 🎉

**Comment by Kethku** [comment]
@last-partizan @PyGamer0 @tpict could you try pulling from main to see if your issue is fixed?

**Comment by PyGamer0** [comment]
It works!

**Comment by last-partizan** [comment]
Yes, it works!

**Comment by tpict** [comment]
resolved on my end too, thanks!
