### ISSUE TITLE
Mouse drag interactions with help split window

### ISSUE THREAD

**Issue by krage** [Kethku/neovide#80]
#### Resizing active help window
You can't resize the upper help split window via mouse-dragging its status line while it's the active window.  If you make the window below it active then you can resize via the now-inactive status line of that upper help window. Keyboard resizing via eg. `C-w, +` while it's active works fine.  Ordinary splits don't have this restriction.

#### Selecting text within help window
Attempting to select text within a help window via mouse drag never succeeds. Instead it appears to always attempt to jump to a help topic associated with whatever word the drag began at (or sometimes even a fragment of that word?) whether or not that term is highlighted as a linked topic or exists as one within the help system.  Selecting text via mouse drag in normal splits works fine.

---

Bumped into this today when clicking into neovide window to refocus it.  While refocusing the window it also jumped to an unrelated help topic.  It seems I must've input not just a click but a brief drag in the help window that was open.  Other mouse interactions like clicks to change cursor position, double-clicks to follow topic links, and mousewheel scroll in help splits all seem to work fine.

These issues seem specific to neovide and both exist without any user config present. Neither are an issue in nvim-qt using the same underlying nvim, nor in plain old gvim even.

**Comment by Kethku** [comment]
Thanks for the details! I'm looking into it now.

**Comment by Kethku** [comment]
Should be fixed now.

**Comment by Kethku** [comment]
As some background, apparently neovim doesn't like it if a gui sends multiple drag events without actually changing grid position. The naive implementation of a gui would send a drag event any time the mouse moves at all with the associated grid position. This causes the problem you identified, so I changed the window code to only send mouse drag events if the grid position changed between frames. This fixed the jumping cursor problem, but I'm not positive if it fixed the resizing problem you mentioned since I didn't fully understand it. If it is still an issue please reopen and I will look further

**Comment by krage** [comment]
I've rebuilt the latest and it looks like that fixes both problems, thanks!  Given that the same interactions worked in nvim-qt with the same nvim I was suspecting a communication issue between neovide and nvim like you mention. It seems odd that this only caused these particular problems within help windows rather than universally though.

**Comment by Kethku** [comment]
The issue was visible universally which is why I had a hunch for where the problem was :)
