### ISSUE TITLE
Line ordering issues when scrolling under heavy load

### ISSUE THREAD

**Issue by jonvaldes** [Kethku/neovide#86]
Example. Notice the line numbers:
![image](https://user-images.githubusercontent.com/48644/73441923-224ce500-4354-11ea-9f0f-9d28d9b77f3d.png)

I'm just scrolling up/down while my computer is hammered by other processes consuming all available CPU power. The internal nvim buffers seem to preserve ordering correctly. All editing seems to work with the correct line ordering. This looks like just a rendering issue.

Edit: I should note this seems to happen for lines that come into view when scrolling. Once a line is in view, it remains as it is until it goes out of view. Sometimes, moving the cursor over the line will make the correct characters appear.

**Comment by Kethku** [comment]
I believe this is highly related to https://github.com/Kethku/neovide/issues/41. Frustratingly I also think it is a race condition that I'm struggling to track down. This issue started when I swapped to using async and nvim-rs which fixed a ton of other bugs but introduced this one... 

Weirdly it's preserved when scrolling which seems to indicate to me that either the editor structure is missing a redraw event (or parsing it incorrectly) or it is parsing the clear portions of grid lines wrong. This one has been bothering me :/

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jonvaldes** [comment]
I've been toying around with this, and I don't know if it completely fixes this issue, but this change seems to at least make it better (at least for me):

```
 async fn handle_current_commands(receiver: &mut UnboundedReceiver<UiCommand>, nvim: &Neovim<Compat<ChildStdin>>) -> bool {
     if let Some(commands) = drain(receiver).await {
-        let (resize_list, other_commands): (Vec<UiCommand>, Vec<UiCommand>) = commands
-            .into_iter()
-            .partition(|command| command.is_resize());
-        if let Some(resize_command) = resize_list.into_iter().last() {
-            resize_command.execute(&nvim).await;
-        }
-
-        for ui_command in other_commands.into_iter() {
-            ui_command.execute(&nvim).await;
+        for command in commands {
+            command.execute(&nvim).await;
         }
```

I also have no idea why you were splitting off the resize events, so this might introduce other issues around that...

**Comment by Kethku** [comment]
Interesting. To be honest I don't remember why I split those off. Could you try that for a while and let me know here if you run into it again?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Kethku** [comment]
Maybe nvim uses resize occasionally to clear... That'd be weird...

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Kethku** [comment]
I'm pretty sure the ui events have nothing to do with the rendering. There are two kinds of events passed around in the app today: UiCommands and RedrawEvents. 

The UiCommands are like key inputs, mouse clicks and window resizes. The resize events were split off because thats a particularly slow operation, so I wanted to only run the latest one if there were a series.

RedrawEvents are all of the neovim events for drawing the screen. The full list can be found here: https://github.com/neovim/neovim/blob/master/runtime/doc/ui.txt The processing of these is likely to be the culprit for the rendering artifacts

**Comment by jonvaldes** [comment]
My previous change did indeed not solve the issue, just make it more rare when running on release (probably different timing, making it more difficult to hit by pure chance). On debug, though, I'm still seeing issues like this:
![2020-01-30 20_49_51-Neovide](https://user-images.githubusercontent.com/48644/73484731-21db3b00-43a2-11ea-913d-265aee6fa612.png)
(There should be just one opening and one closing bracket in that image).
Going over that area in visual mode triggers a redraw of the area, and the correct text shows up

**Comment by Kethku** [comment]
How embarrassing... I may have to write some repetitive tests to try and get it to happen

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jonvaldes** [comment]
I found an easy way to reproduce the issue.

Add this line:
```
index c161a21..6691b69 100644
--- a/src/window.rs
+++ b/src/window.rs
@@ -170,6 +170,7 @@ pub fn ui_loop() {
             Event::RedrawRequested { .. } => {
                 let frame_start = Instant::now();

+                std::thread::sleep(std::time::Duration::from_millis(800));
                 if REDRAW_SCHEDULER.should_draw() {
                     if let Err(e)  = skulpin_renderer.draw(&window, |canvas, coordinate_system_helper| {

```
Then open a big file, and keep the J key pressed for a while. You'll soon start seeing weird things like the last image I posted.

I'll keep poking around, see if I can find the source of this issue

**Comment by Kethku** [comment]
Thanks so much for investigating!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Kethku** [comment]
This will definitely help when testing it out

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Kethku** [comment]
Something I noticed was that since the error is preserved through scrolling, it pretty much garentees the problem is stored in the editor structure. This doesn't mean the drawing isn't involved, but I feel like it's probably some interaction with the redraw commands where it is missing some clear command or similar... Hard to tell

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jonvaldes** [comment]
I experimented a bit. I've pretty much ruled out the scroll_region function now (I was a bit suspicious of that one). I reimplemented it in a different way, and the problem persisted. I'll prod it a bit more if I have some spare time

**Comment by Kethku** [comment]
I'd be interested in any refactors you made. I built scroll_region in an afternoon and then just went with it. If its an improvement but doesn't fix the problem I'd still take it

**Comment by Kethku** [comment]
I'm going to first implement pretty extensive logging to track whether we are actually getting the clear redraw events. If we are, then its obviously some weird race condition. If not, Im going to look at nvim-rs's internals to see if there is some race condition there which causes events to be missed.

**Comment by Kethku** [comment]
Then if we still haven't figured it out I will take a stab at writing some kind of automated test. I don't think the renderer is necessary to cause the problem, so it would be interesting to write a test which starts neovim, opens a large file, and scrolls around a ton. if the file is a bunch of unique lines, I could catch the issue by looking for editor grid lines which have repeated characters above and below. Further since it seems like the problem happens more on clear than redraw, I will make alternating lines differ in length so that we might catch it that way

**Comment by Kethku** [comment]
Its going to take a bit but I'm confident we'll be able to track it down

**Comment by KillTheMule** [comment]
> Im going to look at nvim-rs's internals

I've given this some thought, and it might indeed be a problem of nvim-rs. Specifically, [this](https://github.com/KillTheMule/nvim-rs/blob/master/src/neovim.rs#L244) might be the culprit: We spawn notification handling onto the executor, but I don't think it guarantees some order of execution, especially not when using threads (tokio's default), especially not under load. Could you insert some logging into the handler function to see if that's indeed the problem here? If you can confirm this, one particular mitigation might be switching to tokio's basic schedular, which is single-threaded and might have a more deterministic order of execution.

 Still, this very much touches upon the fundamental async design, and will need to be solved in nvim-rs (even if it's not the culprit in this case, even though I think that's it, just needs confirmation). It makes 100% sense that notifications and requests should be handled in the order they arrive, no exceptions, so I'll have to come up with something. No idea what, but I think I'll try to investigate what the python client does here.

Ok, so, if you could try to confirm I'll put that on the top of my list for nvim-rs, although I'm very much pressed for time these days and have not yet finished integrating gio... sigh, so much to do :D

**Comment by jonvaldes** [comment]
The machine I use has a pretty high core count (16 cores, plus hyperthreading), so it makes sense I would get hit particularly badly by this issue, as this machine will create many more opportunities for different thread orderings than others.

**Comment by Kethku** [comment]
I forked nvim-rs and added a simple queue which takes parsed messages from the neovim process, and places them in a queue before processing them with the handler. Then I added a loop which processes the messages one after another. The PR can be found here https://github.com/KillTheMule/nvim-rs/pull/13.

I implemented it as a complete hack and didn't handle results properly, but I think I've confirmed it solves the core issue because I haven't seen the issue happen since in my local branch which uses the fork! Incidentally it also solves another bug I was at a loss for :)

So I'm going to continue using it locally and report back here if anything changes. @KillTheMule balls in your court I think.

**Comment by Kethku** [comment]
I believe this is solved by the hack I made in the above referenced PR, so I have pushed an updated Cargo.toml which references my branch and will update that once it gets fixed upstream (either by my hack or a similar fix). That said, it is hard for me to tell if it is really fixed given the nondeterministic nature of the problem and the fact that I am currently away from home and don't have access to my desktop which has more cores, so @jonvaldes if you could play around with it and let me know if you see the problem again that would be great.

**Comment by jonvaldes** [comment]
Yup, I'm also unable to repro the issue with the new code.
Thanks a lot! :)

**Comment by KillTheMule** [comment]
It's been some time, but could you try https://github.com/Kethku/neovide/pull/344 to see if that fixes the issue, too? I'd be really grateful :)
