### ISSUE TITLE
add support for "Edit in neovide" similar to gvim

### ISSUE THREAD

**Issue by prabirshrestha** [Kethku/neovide#94]
cmd arg or `:Neovide explorer install` `:Neovide explorer uninstall`

**Comment by Kethku** [comment]
I think this is interesting to add, but at the moment it is pretty low on the priority list given other bug fixes and more general features. I would be willing to accept a PR though. I suspect it should be as simple as writing to a registry and building a way to delete from the registry.

If a PR is made which hacks it in in some way, I can go in and implement it as a command arg correctly. I just don't have the time to go debug how to install an explorer option properly and hygienically.

**Comment by prabirshrestha** [comment]
This is for just "open cmd here".

```reg
Windows Registry Editor Version 5.00

;Created by Vishal Gupta for AskVG.com

[HKEY_CLASSES_ROOT\Directory\Background\shell\askvgcmd]
@="@shell32.dll,-8506"
"Extended"=""
"NoWorkingDirectory"=""

[HKEY_CLASSES_ROOT\Directory\Background\shell\askvgcmd\command]
@="cmd.exe /s /k pushd \"%V\""

[HKEY_CLASSES_ROOT\Directory\shell\askvgcmd]
@="@shell32.dll,-8506"
"Extended"=""
"NoWorkingDirectory"=""

[HKEY_CLASSES_ROOT\Directory\shell\askvgcmd\command]
@="cmd.exe /s /k pushd \"%V\""

[HKEY_CLASSES_ROOT\Drive\shell\askvgcmd]
@="@shell32.dll,-8506"
"Extended"=""
"NoWorkingDirectory"=""

[HKEY_CLASSES_ROOT\Drive\shell\askvgcmd\command]
@="cmd.exe /s /k pushd \"%V\""

```

**Comment by nganhkhoa** [comment]
I have the command installed manually, maybe I can do this as my first issue.

**Comment by Kethku** [comment]
@nganhkhoa that would be awesome! If you have an idea for how to integrate this it would be great to have

**Comment by nganhkhoa** [comment]
Sorry for the delay, I've been quite busy.
So I just looked up on Neovide implementation on command handling. I noticed that we are not buffering the user input and instead send directly to the underlying nvim process.

This will make control of handling custom user command harder in the future, so I just want to make sure I don't jump in and implement by myself.

The current implementation lies in `windows.rs/handle_keyboard_input`, every key code captured is sent to nvim through Bridge. Maybe we should make a buffer here when the user is in the normal mode and process when the enter key is hit. In other cases, the input is sent immediately.

Will this makes sense? We could make a function to handle specific commands from neovide by checking the first few bytes of the buffer to be equals to some custom command set. Else, the command is sent to nvim, the same logic occur.

I also see that we don't store the current vim mode in Bridge (or it is). Should I make a call to check the current vim mode? And we still haven't yet discuss about the drawing, since these command is not sent to nvim, so no feedback on drawing and we should draw the command string ourselves?

Another option, I may propose, we could just add the Registry key on startup. No one have to enter any command at all. But we shouldn't, should we?

---

On implementation of "Edit in Neovide", I have some code uses Rust to implement this already, through winapi. We will be updating these registry keys:

`\\Registry\\Root\\Directory\\Background\\shell\\neovide` (1) and `\\Registry\\Root\\Directory\\Background\\shell\\neovide\\command` (2)

(1) has the two values: (Default) "Edit in Neovide", and (Icon) "Path/to/neovide.exe"

(2) has (Default) `"Path/to/neovide" "%V"`

These registries are for folders, files registry should have the same content residing in `\\Registry\\Root\\*\\shell\\neovide` with `..\\command` (Default) as `"Path/to/neovide" "%1"`

I tested these registry on my machine already, everything can be done quite fast if we have resolved the aforementioned problem.

**Comment by nganhkhoa** [comment]
Oh yes, I didn't notice that `rpcnotify` can be used to generate request. I will register this command and add in `bridge/handler.rs`. Will implement when I have time though.

**Comment by nganhkhoa** [comment]
It quite messy, but I got the first lines of code ready. I have to setup a client in neovim using `set_client_info` to have the channel id for rpcnotify. Then retrieve the channel id by parsing the `get_list_chans`. I was able to receive the command in `BRIDGE/handler.rs` now. Now I need to check the admin rights. If it goes well, we have the feature semi-complete by the end of this week.

**Comment by prabirshrestha** [comment]
I was looking into cleaningup my dotfiles and I noticed that I have an `.inf` file that allows you to install explorer dropdown as well as add it to control panel. https://github.com/prabirshrestha/dotfiles/blob/3b3a1079e7a3505a1e34eeb0922ba09c1fd10d23/Console2Here.inf

You can right click the `.inf` and click "Install" in windows.

**Comment by nganhkhoa** [comment]
@prabirshrestha this seems interesting, but the file is hardcoded with the path. If we can generate the file and ask the user to click it though. But the feature I added is almost complete, only admin check and error reporting left. So this might not be used, but thanks for your suggestion.

**Comment by Kethku** [comment]
@nganhkhoa i think the PR you created got merged. Is this in?

**Comment by Kethku** [comment]
Ah no I'm an idiot. It still says WIP

**Comment by nganhkhoa** [comment]
I would need to make the tokio to block the error message to merge. If the code fail it will output the error message on neovim.

**Comment by eight04** [comment]
Is it possible to open the file in a running instance with a new window or tab?
